/**
 * Slugs that cannot become a tenant, because the slug is also the subdomain
 * `<slug>.dominio.com.br` (specs/arquitetura/multi-tenant.md): reserving these
 * stops a prefecture from hijacking an infrastructure/application hostname.
 *
 * Exported so the self-service onboarding UI (post-M0) can render the list as
 * a table. Every entry already satisfies the slug format whitelist; `.well-known`
 * needs no entry (the leading dot fails the format check), so only the bare
 * `well-known` is listed.
 */
export const RESERVED_TENANT_SLUGS: ReadonlySet<string> = new Set([
  // Infra / network
  "www",
  "ftp",
  "mail",
  "smtp",
  "pop",
  "imap",
  "webmail",
  "ns",
  "ns1",
  "ns2",
  "dns",
  "localhost",
  "host",
  "server",
  // App / API / auth
  "api",
  "graphql",
  "rest",
  "webhook",
  "webhooks",
  "ws",
  "wss",
  "app",
  "admin",
  "dashboard",
  "console",
  "panel",
  "system",
  "auth",
  "login",
  "logout",
  "signin",
  "signup",
  "register",
  "oauth",
  "sso",
  "status",
  "health",
  "ping",
  "metrics",
  "cdn",
  "static",
  "assets",
  "media",
  "images",
  "img",
  "video",
  // Dev environments
  "dev",
  "develop",
  "development",
  "staging",
  "test",
  "testing",
  "qa",
  "homolog",
  "homologation",
  "sandbox",
  "prod",
  "production",
  "local",
  "demo",
  "demo2",
  // Business / marketing / comms
  "blog",
  "docs",
  "support",
  "help",
  "helpdesk",
  "faq",
  "forum",
  "community",
  "shop",
  "store",
  "cart",
  "checkout",
  "pay",
  "billing",
  "payments",
  "about",
  "contact",
  "terms",
  "privacy",
  "legal",
  "security",
  "jobs",
  "careers",
  "press",
  "news",
  "newsletter",
  // System / security patterns
  "well-known",
  "autodiscover",
  "mta-sts",
]);
